[package]
name = "diesel_demo"
version = "0.1.0"
authors = ["bart <bwillems@protonmail.com>"]

[dependencies]
diesel = { version = "0.15.0", features = ["postgres"] }
diesel_codegen = { version = "0.15.0", features = ["postgres"] }
dotenv = "0.9.0"
dotenv_macros = "0.10.0"
r2d2 = "*"
r2d2-diesel = "*"
rocket = "0.3.0"
rocket_codegen = "0.3.0"
rocket_contrib = "0.3.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"