[package]
name = "youkebox"
description= "YoukeBox, a better way to create live playlists"
version = "0.1.0"
authors = ["bart <bwillems@protonmail.com>"]
license-file = "LICENSE"
repository = "https://github.com/BartWillems/YoukeBox-rust"
readme = "README.md"
categories = ["web-programming"]

[dependencies]
chrono = "0.4"
diesel = { version = "0.16.0", features = ["postgres"] }
diesel_codegen = { version = "0.16.0", features = ["postgres"] }
dotenv = "0.9.0"
dotenv_macros = "0.10.0"
r2d2 = "0.7.4"
r2d2-diesel = "0.16.0"
reqwest = "0.8.0"
rocket = "0.3.3"
rocket_codegen = "0.3.3"
rocket_contrib = "0.3.3"
rocket_cors = "0.2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
lazy_static = "0.2"

[badges]
maintenance = { status = "actively-developed" }