[global]
port = 8000
limits = { forms = 32768 }

[development]
address = "localhost"
log = "normal"

[staging]
address = "0.0.0.0"
log = "normal"

[production]
address = "0.0.0.0"
log = "critical"
secret_key = "please_enter_a_secret_key"